name: Test and publish to PyPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Install my package
      run: |
        python -m pip install .

    - name: Install test dependencies
      run: |
        pip install flake8 pytest coverage

    - name: Test with pytest
      run: |
        coverage run -m pytest
      
    - name: Clean up coverage data
      run: |
        # This is a workaround for the fact that the `[coverage:paths]` section
        # of `setup.cfg` is not actually applies until we run `combine`; so we
        # rename the report such that we can then "combine" it.
        mv .coverage .coverage.hack
        coverage combine
        coverage report

    - uses: codecov/codecov-action@v1

    - name: Build
      run: |
        python setup.py sdist bdist_wheel

#     - name: Publish to Test PyPI (always)
#       uses: pypa/gh-action-pypi-publish@master
#       with:
#         user: __token__
#         password: ${{ secrets.test_pypi_password }}
#         repository_url: https://test.pypi.org/legacy/

    - name: Publish to PyPI (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
